# Generated by Django 5.2 on 2025-06-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='pdf',
            new_name='pdf_fayl',
        ),
    ]
